// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jazqkngsgebefagibnia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphenFrbmdzZ2ViZWZhZ2libmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTQzOTcsImV4cCI6MjA3MDQ3MDM5N30.eJ3xjqGhq4mfd1bzogztg-Ao2TQs2EY9v0XwJb7R9MQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});